name: Cypress Tests

on:
  push:
    branches: [main]

  pull_request_target:
    types: [labeled, opened, synchronize, reopened]
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Packages
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: |
            pnpm install --frozen-lockfile
          start: pnpm start
          wait-on: "http://localhost:3000"
          browser: chrome
          config: timeout=100000
          config-file: cypress.config.ts
        env:
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
